### ISSUE TITLE
digicampipe.io.protozfitsreader not reading

### ISSUE THREAD

**Issue by calispac** [calispac/digicampipe#53]
I am currently redoing a fresh install on a cluster machine at unige. After facing some problem detailed in #52 I finnaly manage to have all imports work.

However when I try to read files I get the following error.

```bash
/home/alispach/.anaconda3/envs/digicampipe/lib/python3.5/site-packages/matplotlib/figure.py:1999: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  warnings.warn("This figure includes Axes that are not compatible "
Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file /sst1m/raw/2017/10/30/SST1M01/SST1M01_20171030.000.fits.fz and table RunHeader

/home/alispach/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:186: UserWarning: /sst1m/raw/2017/10/30/SST1M01/SST1M01_20171030.000.fits.fz has no RunHeader
  "{} has no RunHeader".format(self.fname))
This columns (6.1.5) is supposed to be ignored at some point...
Segmentation fault
```

The file I used is from second Crab observation of th 30th october 2017 which I believe is what was used for making the test files.

If I try to open older files (from first Crab observations in `/sst1m/raw/2017/09/28/SST1M01/`) then I don't encounter this problem (I can read the file and no Segmentation Fault). I get two warnings (which are expected) : 

```bash
Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file /sst1m/raw/2017/09/28/CRAB_01/CRAB_01_20170928.000.fits.fz and table RunHeader
/home/alispach/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:185: UserWarning: /sst1m/raw/2017/09/28/CRAB_01/CRAB_01_20170928.000.fits.fz has no RunHeader
  "{} has no RunHeader".format(self.fname))
/home/alispach/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:264: UserWarning: Could not read `hiGain.waveforms.baselines` for event:1of run_id:0
  "of run_id:{1}".format(self.event_id, self.run_id)
```

**Comment by dneise** [comment]
@calispac can you send me these two files?

**Comment by Etienne12345** [comment]
Why are you guys trying to read the RunHeader table ? There is no such table in our files. If there was some in some files, it was a mistake during data taking. The table of interest is "Events"

**Comment by Etienne12345** [comment]
Looks to me that there is an issue with the reading of the baselines, as the newer files that fail for cyril do have baselines, while older ones do not. I can load all files correctly with the zfitsviewer, and I cannot find the error message in my code: I'll keep investigating...

**Comment by Etienne12345** [comment]
Found the error message in an old version of the C++ reader. It basically means that the reader does not know about this column, i.e. outdated data moel. Are you sure that you installed the latest version of the python package ? Or that you do not have an older version of the CamerasToACTL project installed somewhere on your machine (and which libs would be used instead of the correct ones) ?

I'll try to generate a new version of the package today, and generate it for python 3.6 too.

**Comment by Etienne12345** [comment]
Done. New versions available. Should not change anything really, only some error messages might be improved:
http://www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.43.Python3.5.Linux.x86_64.tar.gz
and
http://www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.43.Python3.6.Linux.x86_64.tar.gz

**Comment by dneise** [comment]
We are reading the RunHeader, because the reader I reworked was written in a way, that it tries to read the runheader and if it does not exist it falls back to assign the `run_id = 0`. It used to `print()` and I just modified this print to be a `warning` now. 

Warnings can be ignored.

So this:

> /home/alispach/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:185: UserWarning: /sst1m/raw/2017/09/28/CRAB_01/CRAB_01_20170928.000.fits.fz has no RunHeader "{} has no RunHeader".format(self.fname))

Is a `UserWarning` and can be ignored.

This:

> /home/alispach/ctasoft/digicampipe/digicampipe/io/protozfitsreader.py:264: UserWarning: Could not readhiGain.waveforms.baselinesfor event:1of run_id:0 "of run_id:{1}".format(self.event_id, self.run_id)

Is also a `UserWarning` and can be ignored

This:

> Open has failed. Error: Table RunHeader could not be found in input file. Aborting. while reading file /sst1m/raw/2017/09/28/CRAB_01/CRAB_01_20170928.000.fits.fz and table RunHeader 

Does not come from the Python side. At least I have not seen it inside `digicampipe.io.protozfitsreader.py`. 

However the problem is the SegFault

**Comment by Etienne12345** [comment]
Still, I do not get the point of keeping warning messages that are bound to be always here. 

For the the C++ messages: 
1. "Open has failed" you will get it as long as you keep trying to open a table that does not exist (i.e. RunHeader)
2. The segfault is somehow not really the problem: Cyril is somehow using an old version of the reader package. Once he "moves back" to the new version things should work again. The reason for the segfault is the following: As the data model evolves, new fields are added, hence older IO packages have no idea how to deal with this new data. I could have made them silently ignore "what it does not understand" but I prefer to make it crash instead because people take care of crashes, while silent vetos can be ignored for a while and create much more complicated issues later on (if they are ever discovered).

**Comment by dneise** [comment]
> Still, I do not get the point of keeping warning messages that are bound to be always here.

Me to ... I just did not **know** that there will never be a RunHeader ... I just refactored code, which was trying to read a RunHeader, so after my modifications this behaviour was of course still the same.

This "there will never be a runheader" is new to me. Still you are right ... let's kick code, which is useless.

If things change in the future and we get a runheader ... we can still start to read it

**Comment by dneise** [comment]
> Done. New versions available. Should not change anything really, only some error messages might be improved:
http://www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.43.Python3.5.Linux.x86_64.tar.gz
and
http://www.isdc.unige.ch/~lyard/repo/ProtoZFitsReader-0.43.Python3.6.Linux.x86_64.tar.gz

That's great thanks

**Comment by calispac** [comment]
This is solved in #52
